### ISSUE TITLE
Bros making 10000 commits for a readme

### ISSUE THREAD

**Issue by downgear** [khoakomlem/khoakomlem#1]
# Author: Culove

**Comment by downgear** [comment]
Would you hold me tight and not let go 

![GbxTdWYbMAAZDZ8.png](https://github.com/user-attachments/assets/e3151e4a-54e2-42fe-932d-c6df95480f63)

**Comment by beanbocchi** [comment]
umm

**Comment by beanbocchi** [comment]
umm I think we should not close this as completed

**Comment by downgear** [comment]
my life my rules

**Comment by downgear** [comment]
shouldve opened

**Comment by beanbocchi** [comment]
bruh
